# Generated by Django 5.2.4 on 2025-07-28 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField(default=datetime.datetime(2025, 7, 28, 14, 0, 4, 607494))),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
